version: '3'
services:
  frontend:
    container_name: frontend
    build: './frontend/'
    ports:
      - 3000:3000
    volumes:
      - './frontend:/app'
    tty: true
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exchange-trading
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080